### ISSUE TITLE
Need some help getting your ZombieGenerator  PS to run...

### ISSUE THREAD

**Issue by Rickcau** [guyrleech/General-Scripts#2]
I have an scenario in-which I need to create some Zombies for testing and I came across your article.  I downloaded the PS and I cannot get it to run.

I am trying the following command: 
PS C:\work\zombieGenerator> '.\ZombieGenerator.ps1' -pids 3700,9952 -numberOfHandles 100

I have opened two instances of Notepad.exe and I the two Pids are 3700 and 9952.  I am getting the following error message.
PS C:\work\zombieGenerator> '.\ZombieGenerator.ps1' -pids 3700,9952 -numberOfHandles 100
At line:1 char:25
+ '.\ZombieGenerator.ps1' -pids 3700,9952 -numberOfHandles 100
+                         ~~~~~
Unexpected token '-pids' in expression or statement.
At line:1 char:31
+ '.\ZombieGenerator.ps1' -pids 3700,9952 -numberOfHandles 100
+                               ~~~~
Unexpected token '3700' in expression or statement.
At line:1 char:41
+ '.\ZombieGenerator.ps1' -pids 3700,9952 -numberOfHandles 100
+                                         ~~~~~~~~~~~~~~~~
Unexpected token '-numberOfHandles' in expression or statement.
At line:1 char:58
+ '.\ZombieGenerator.ps1' -pids 3700,9952 -numberOfHandles 100
+                                                          ~~~
Unexpected token '100' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

The version of powershell I am running is "Windows PowerShell ISE (x86)

**Comment by guyrleech** [comment]
When you run a PowerShell script which is enclosed in quotation marks, usually because there are spaces in the path, you need to prefix it with the & character otherwise it will be considered as a string literal and the subsequent -* arguments are effectively confusing PowerShell. Another solution is to drop the quotes around .\ZombieGenerator.ps1 since they are not required because there are no spaces in the path/name, assuming that the script is present in your current working directory.

**Comment by guyrleech** [comment]
Not a problem with the script
